version: 0.2

env:
  variables:
    IMAGE_NAME: devops-backend

phases:
  pre_build:
    commands:
      - echo Logging into DockerHub
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$COMMIT_ID
      - echo Image tag is $IMAGE_TAG

  build:
    commands:
      - echo Building backend image
      - cd backend
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing image
      - docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
      - docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
      - chmod +x scripts/update-values.sh
      - ./scripts/update-values.sh