apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-helm
data:
  DB_HOST: mysql-helm
  DB_NAME: testdb

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret-helm
type: Opaque
data:
  DB_USER: {{ "root" | b64enc }}
  DB_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}