apiVersion: v1
kind: Service
metadata:
  name: mysql-helm
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-helm
spec:
  serviceName: mysql-helm
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret-helm
              key: DB_PASSWORD

        - name: MYSQL_DATABASE
          value: testdb

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
          subPath: mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: {{ .Values.mysql.storage }}